In [23]:
import librosa
import librosa.display
import IPython.display
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import os
import ast
import pickle
import random


num_of_test_data = 100


def DATA_PROCCESS_FROM_LIBROSA(AUDIO_PATH, wave_data_set):
    y, sr = librosa.load(AUDIO_PATH)
    S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128, fmax=8000)
    mfcc_len = S.shape[1]
    
    need_batch_x = 300-mfcc_len
    
    S = np.append(S,np.zeros([128,need_batch_x]))
    
    if wave_data_set==[]:
        wave_data_set = np.append(wave_data_set, S)
        print("shape: ",wave_data_set.shape) 
    else:        
        wave_data_set = np.vstack((wave_data_set, S))
        print(wave_data_set)
        
    wave_data_set = np.array(wave_data_set)
    return wave_data_set
    
def ONE_HOT_ENCODE(num,data_max_num):
    vector = np.zeros(data_max_num)
    vector[num]=1
    return vector

def ELBAROSA_DATA_INCOME():
    DATA_PATH_NAME = "./temporary_data"
    
    label = []
    wave_data_set = []
    for root, dirs, files1 in os.walk(DATA_PATH_NAME):
        print(dirs)
        for dir_name in dirs:
            file_path = DATA_PATH_NAME+'/'+dir_name
            for root,dirs,files in os.walk(file_path):
                print(dirs)
                print(files)
                for file_name in files:
                    label.append(file_name.split()[0])
                    print(file_name)
                    wave_data_set = (DATA_PROCCESS_FROM_LIBROSA(file_path+'/'+file_name, wave_data_set))
                    print(file_name)
    

    wave_answer_check = label
    wave_answer_set = label



    label = set(label)
    label = list(label)
    data_name = label
    data_index = 0
    
    print("data_length :",end = '')
    print(len(label))
    
    print(label)
    print("fin")
    for data in wave_answer_set:
        i=0
        for data_name in label:
            if data_name==data:
                wave_answer_set[data_index] = ONE_HOT_ENCODE(label.index(data),len(label))
                print(wave_answer_set[data_index])
                data_index+=1 
    for i in range(len(wave_answer_check)):
        print(str(wave_answer_set[i])+":"+str(wave_answer_check[i]))
        
    return wave_data_set, wave_answer_set, len(label)

def VECTOR_DATA_SAVE(wave_data_set, wave_answer_set, label_length):
    with open('ELBAROSA_DATA_HYUNDAI_BETA_COMBINED','wb') as wave_data_set_text:
        pickle.dump(wave_data_set, wave_data_set_text)
    
    with open('ELBAROSA_ANSWER_DATA_HYUNDAI_BETA_COMBINED','wb') as wave_answer_set_text:
        pickle.dump(wave_answer_set, wave_answer_set_text)
    
    with open('LABEL_ELBAROSA_DATA_HYUNDAI_BETA_COMBINED','wb') as label_length_text:
        pickle.dump(label_length, label_length_text)
    
    
def VECTOR_DATA_LOAD():
    with open('./ELBAROSA_DATA_HYUNDAI_DEMO_2','rb') as wave_data_set_text:
        wave_data_set = pickle.load(wave_data_set_text)
    
    with open('./ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO_2','rb') as wave_answer_set_text:
        wave_answer_set = pickle.load(wave_answer_set_text)
    
    with open('./LABEL_ELBAROSA_DATA_HYUNDAI_DEMO_2','rb') as label_length_text:
        label_length = pickle.load(label_length_text)
    
    
    return wave_data_set, wave_answer_set, label_length
    
def random_number_income(number_of_random_num, total_data_length):
    random_list = [random.randint(0,total_data_length-1)]
    
    for i in range(number_of_random_num-1):
        random_num = random.randint(0,total_data_length-1)
        while random_num in random_list:
            random_num = random.randint(0,total_data_length-1)
            print(random_num)
            print(random_list)
        random_list.append(random_num)
        
    return random_list
    

def draw_graph(sample,vector_length1,vector_length2):
    plt.plot(sample)
    plt.imshow(np.reshape(sample,(vector_length1,vector_length2)))
    plt.show()

In [13]:
wave_data_set, wave_answer_set, vector_length = VECTOR_DATA_LOAD()


In [7]:
a1 = wave_data_set
a2 = wave_answer_set
a3 = vector_length



In [15]:
ELBAROSA_DATA_HYUNDAI_DEMO_0 = a1
ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO_0 = a2
LABEL_ELBAROSA_DATA_HYUNDAI_DEMO_0 = a3

  

In [8]:
a1.shape

(3151, 38400)

In [11]:
ELBAROSA_DATA_HYUNDAI_DEMO_1 = wave_data_set
ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO_1 = wave_answer_set
LABEL_ELBAROSA_DATA_HYUNDAI_DEMO_1 = vector_length

  

In [14]:
ELBAROSA_DATA_HYUNDAI_DEMO_2 = wave_data_set
ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO_2 = wave_answer_set
LABEL_ELBAROSA_DATA_HYUNDAI_DEMO_2 = vector_length


In [16]:
VECTOR_DATA_SAVE(ELBAROSA_DATA_HYUNDAI_DEMO_0+ELBAROSA_DATA_HYUNDAI_DEMO_1+ELBAROSA_DATA_HYUNDAI_DEMO_2
                ,ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO_0+ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO_1+ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO_2
                ,LABEL_ELBAROSA_DATA_HYUNDAI_DEMO_0+LABEL_ELBAROSA_DATA_HYUNDAI_DEMO_1+LABEL_ELBAROSA_DATA_HYUNDAI_DEMO_2)

ValueError: operands could not be broadcast together with shapes (3151,38400) (6223,38400) 

In [22]:
COMBINED_ELBAROSA_DATA_HYUNDAI_DEMO = np.vstack([ELBAROSA_DATA_HYUNDAI_DEMO_0,ELBAROSA_DATA_HYUNDAI_DEMO_1,ELBAROSA_DATA_HYUNDAI_DEMO_2])
COMBINED_ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO = np.vstack([ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO_0,ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO_1,ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO_2])
COMBINED_LABEL_ELBAROSA_DATA_HYUNDAI_DEMO = np.vstack([LABEL_ELBAROSA_DATA_HYUNDAI_DEMO_0, LABEL_ELBAROSA_DATA_HYUNDAI_DEMO_1, LABEL_ELBAROSA_DATA_HYUNDAI_DEMO_2])


In [24]:
VECTOR_DATA_SAVE(COMBINED_ELBAROSA_DATA_HYUNDAI_DEMO, COMBINED_ELBAROSA_ANSWER_DATA_HYUNDAI_DEMO, COMBINED_LABEL_ELBAROSA_DATA_HYUNDAI_DEMO)

OverflowError: cannot serialize a bytes object larger than 4 GiB

In [24]:
a2

[array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1.